name: Bug Report (Only for servers which are officially supported)
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - EinsLucaaa
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: type
    attributes:
      label: Bug-Type
      description: What kind of problem do you have?
      options:
        - A language on a server is not detected
        - A game mode on a server is not detected
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
